package tests;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import pages.*;

import java.time.Duration;

/**
 * Prod feature tests — generated by TestForge from execution-verified runs.
 * Contains 2 tests:
 *   - Clicking a product opens its detail page with name and price
 *   - Product detail page for Nokia lumia 1520 shows correct name and price
 */
public class ProdTests {

    private WebDriver driver;
    private WebDriverWait wait;
    private RootPage rootPage;
    private ProdPage prodPage;

    @BeforeMethod
    public void setUp() {
        ChromeOptions options = new ChromeOptions();
        // On CI (GitHub Actions sets CI=true) there is no display, so run headless.
        // Locally it stays headful so you can watch; force headless with -Dheadless=true.
        boolean headless = System.getenv("CI") != null || Boolean.getBoolean("headless");
        if (headless) {
            options.addArguments("--headless=new", "--no-sandbox",
                    "--disable-dev-shm-usage", "--disable-gpu");
        }
        options.addArguments("--window-size=1920,1080", "--disable-notifications", "--remote-allow-origins=*");
        // Selenium Manager (built into Selenium 4) auto-provisions the matching driver.
        driver = new ChromeDriver(options);
        wait = new WebDriverWait(driver, Duration.ofSeconds(15));
        rootPage = new RootPage(driver);
        prodPage = new ProdPage(driver);
    }

    @Test(description = "Clicking a product opens its detail page with name and price")
    public void clickingAProductOpensItsDetailPageWithNameAndPrice() {
        // Step 1: Navigate to DemoBlaze home page
        driver.get("https://www.demoblaze.com");

        // Step 2: Click on Samsung galaxy s6 product link
        rootPage.clickSamsungGalaxyS6ProductLink();

        // Step 3: Assert product name heading is visible on detail page
        Assert.assertTrue(prodPage.getProductNameHeadingText().contains("Samsung galaxy s6"),
                "Expected text 'Samsung galaxy s6' in productNameHeading");

        // Step 4: Assert product price is visible on detail page
        Assert.assertTrue(prodPage.isProductPriceElementVisible(), "productPriceElement should be visible");

        // Step 5: Assert Add to cart button is visible on detail page
        Assert.assertTrue(prodPage.isAddToCartButtonVisible(), "addToCartButton should be visible");

    }

    @Test(description = "Product detail page for Nokia lumia 1520 shows correct name and price")
    public void productDetailPageForNokiaLumia1520ShowsCorrectNameAndPrice() {
        // Step 1: Navigate to DemoBlaze home page
        driver.get("https://www.demoblaze.com");

        // Step 2: Click on Nokia lumia 1520 product link
        rootPage.clickNokiaLumia1520ProductLink();

        // Step 3: Assert product name heading equals Nokia lumia 1520
        Assert.assertTrue(prodPage.getProductNameHeadingText().contains("Nokia lumia 1520"),
                "Expected text 'Nokia lumia 1520' in productNameHeading");

        // Step 4: Assert product price element is visible
        Assert.assertTrue(prodPage.isProductPriceElementVisible(), "productPriceElement should be visible");

    }

    @AfterMethod
    public void tearDown() {
        if (driver != null) driver.quit();
    }
}
