package tests;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import pages.*;

import java.time.Duration;

/**
 * Root feature tests — generated by TestForge from execution-verified runs.
 * Contains 6 tests:
 *   - Home page displays navigation, categories, and product list
 *   - Cart link navigates to the cart page showing cart heading
 *   - Phones category filter displays phone products
 *   - Laptops category filter displays laptop products
 *   - Next and Previous pagination buttons are present on home page
 *   - Contact and About us links are visible in home page navigation
 */
public class RootTests {

    private WebDriver driver;
    private WebDriverWait wait;
    private RootPage rootPage;

    @BeforeMethod
    public void setUp() {
        ChromeOptions options = new ChromeOptions();
        // On CI (GitHub Actions sets CI=true) there is no display, so run headless.
        // Locally it stays headful so you can watch; force headless with -Dheadless=true.
        boolean headless = System.getenv("CI") != null || Boolean.getBoolean("headless");
        if (headless) {
            options.addArguments("--headless=new", "--no-sandbox",
                    "--disable-dev-shm-usage", "--disable-gpu");
        }
        options.addArguments("--window-size=1920,1080", "--disable-notifications", "--remote-allow-origins=*");
        // Selenium Manager (built into Selenium 4) auto-provisions the matching driver.
        driver = new ChromeDriver(options);
        wait = new WebDriverWait(driver, Duration.ofSeconds(15));
        rootPage = new RootPage(driver);
    }

    @Test(description = "Home page displays navigation, categories, and product list")
    public void homePageDisplaysNavigationCategoriesAndProductList() {
        // Step 1: Navigate to DemoBlaze home page
        driver.get("https://www.demoblaze.com");

        // Step 2: Assert the main navigation bar is visible
        Assert.assertTrue(rootPage.isNavigationBarVisible(), "navigationBar should be visible");

        // Step 3: Assert the PRODUCT STORE brand link is visible
        Assert.assertTrue(rootPage.isPRODUCTStoreBrandLinkVisible(), "pRODUCTStoreBrandLink should be visible");

        // Step 4: Assert the CATEGORIES link is visible
        Assert.assertTrue(rootPage.isCATEGORIESLinkVisible(), "cATEGORIESLink should be visible");

        // Step 5: Assert the Phones category link is visible
        Assert.assertTrue(rootPage.isPhonesCategoryLinkVisible(), "phonesCategoryLink should be visible");

        // Step 6: Assert the Laptops category link is visible
        Assert.assertTrue(rootPage.isLaptopsCategoryLinkVisible(), "laptopsCategoryLink should be visible");

        // Step 7: Assert the Monitors category link is visible
        Assert.assertTrue(rootPage.isMonitorsCategoryLinkVisible(), "monitorsCategoryLink should be visible");

        // Step 8: Assert Samsung galaxy s6 product is listed
        Assert.assertTrue(rootPage.getSamsungGalaxyS6ProductLinkText().contains("Samsung galaxy s6"),
                "Expected text 'Samsung galaxy s6' in samsungGalaxyS6ProductLink");

        // Step 9: Assert the Log in link is visible in nav
        Assert.assertTrue(rootPage.isLogInNavLinkVisible(), "logInNavLink should be visible");

        // Step 10: Assert the Sign up link is visible in nav
        Assert.assertTrue(rootPage.isSignUpNavLinkVisible(), "signUpNavLink should be visible");

        // Step 11: Assert the Cart link is visible in nav
        Assert.assertTrue(rootPage.isCartNavLinkVisible(), "cartNavLink should be visible");

    }

    @Test(description = "Cart link navigates to the cart page showing cart heading")
    public void cartLinkNavigatesToTheCartPageShowingCartHeading() {
        // Step 1: Navigate to DemoBlaze home page
        driver.get("https://www.demoblaze.com");

        // Step 2: Click the Cart link in the navigation bar
        rootPage.clickCartNavLink();

        // Step 3: Assert Products table header is visible on cart page
        // TODO not automated in this export: Cart products table header (css=#tbodyid)

        // Step 4: Assert Place Order button is visible on cart page
        // TODO not automated in this export: Place Order button (text=Place Order)

        // Step 5: Assert URL contains cart page reference
        Assert.assertTrue(driver.getCurrentUrl().contains("cart.html"),
                "URL should contain 'cart.html' but was: " + driver.getCurrentUrl());

    }

    @Test(description = "Phones category filter displays phone products")
    public void phonesCategoryFilterDisplaysPhoneProducts() {
        // Step 1: Navigate to DemoBlaze home page
        driver.get("https://www.demoblaze.com");

        // Step 2: Click the Phones category link
        rootPage.clickPhonesCategoryLink();

        // Step 3: Assert Samsung galaxy s6 is visible in filtered list
        Assert.assertTrue(rootPage.getSamsungGalaxyS6ProductLinkText().contains("Samsung galaxy s6"),
                "Expected text 'Samsung galaxy s6' in samsungGalaxyS6ProductLink");

        // Step 4: Assert Nokia lumia 1520 is visible in filtered list
        Assert.assertTrue(rootPage.getNokiaLumia1520ProductLinkText().contains("Nokia lumia 1520"),
                "Expected text 'Nokia lumia 1520' in nokiaLumia1520ProductLink");

    }

    @Test(description = "Laptops category filter displays laptop products")
    public void laptopsCategoryFilterDisplaysLaptopProducts() {
        // Step 1: Navigate to DemoBlaze home page
        driver.get("https://www.demoblaze.com");

        // Step 2: Click the Laptops category link
        rootPage.clickLaptopsCategoryLink();

        // Step 3: Assert Sony vaio i5 is visible in filtered list
        Assert.assertTrue(rootPage.getSonyVaioI5ProductLinkText().contains("Sony vaio i5"),
                "Expected text 'Sony vaio i5' in sonyVaioI5ProductLink");

        // Step 4: Assert Sony vaio i7 is visible in filtered list
        Assert.assertTrue(rootPage.getSonyVaioI7ProductLinkText().contains("Sony vaio i7"),
                "Expected text 'Sony vaio i7' in sonyVaioI7ProductLink");

    }

    @Test(description = "Next and Previous pagination buttons are present on home page")
    public void nextAndPreviousPaginationButtonsArePresentOnHomePage() {
        // Step 1: Navigate to DemoBlaze home page
        driver.get("https://www.demoblaze.com");

        // Step 2: Assert the Previous pagination button is visible
        Assert.assertTrue(rootPage.isPreviousPaginationButtonVisible(), "previousPaginationButton should be visible");

        // Step 3: Assert the Next pagination button is visible
        Assert.assertTrue(rootPage.isNextPaginationButtonVisible(), "nextPaginationButton should be visible");

        // Step 4: Click the Next pagination button
        rootPage.clickNextPaginationButton();

        // Step 5: Assert at least one product link is visible after clicking Next
        Assert.assertTrue(rootPage.isProductListingContainerVisible(), "productListingContainer should be visible");

    }

    @Test(description = "Contact and About us links are visible in home page navigation")
    public void contactAndAboutUsLinksAreVisibleInHomePageNavigation() {
        // Step 1: Navigate to DemoBlaze home page
        driver.get("https://www.demoblaze.com");

        // Step 2: Assert Contact link is visible in navigation
        Assert.assertTrue(rootPage.isContactNavLinkVisible(), "contactNavLink should be visible");

        // Step 3: Assert About us link is visible in navigation
        // TODO not automated in this export: About us nav link (text=About us)

        // Step 4: Assert Home (current) active link is visible
        // TODO not automated in this export: Home active nav link (text=Home (current))

    }

    @AfterMethod
    public void tearDown() {
        if (driver != null) driver.quit();
    }
}
